apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: sample-scratch-repo
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: sample-scratch-repo
    app.kubernetes.io/part-of: sample-scratch-repo
  name: sample-scratch-repo
spec:
  ports:
  - port: 8080
    targetPort: 8080
  selector:
    app.kubernetes.io/instance: sample-scratch-repo
status:
  loadBalancer: {}
